"""add employee_code column

Revision ID: e112aed1191d
Revises: 
Create Date: 2026-06-04 10:55:55.914227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e112aed1191d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_code', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['employee_code'])
        batch_op.create_unique_constraint(None, ['employee_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('employee_code')

    # ### end Alembic commands ###
